apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: server
spec:
  template:
    spec:
      containers:
        - name: server
          image: dhanuka84/gitops-using-argo-cd-and-tekton:dev-ee4d2324d562a16cbc86fb0e14cebb22c5e1f895
